# -*- coding: utf-8 -*-
"""Match_Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TS2BjRl22rsHI7H30CjypXc1PuK_nKf6
"""

import pandas as pd


REQUIRED_SKILLS = ['python', 'java', 'sql']
CGPA_THRESHOLD = 8.0

def calculate_score(row):
    score = 0
    skills = str(row['Skills']).lower()
    for skill in REQUIRED_SKILLS:
        if skill in skills:
            score += 10
    if row['CGPA'] >= CGPA_THRESHOLD:
        score += 20

    return score
valid_apps = pd.DataFrame({
    'Skills': ['Python, SQL', 'Java', 'Python, Machine Learning', 'SQL, Java'],
    'CGPA': [8.5, 7.2, 9.1, 7.8],
    'College': ['University A', 'University B', 'University A', 'University C']
})
valid_apps['Match_Score'] = valid_apps.apply(calculate_score, axis=1)
shortlisted_final = valid_apps.sort_values(by='Match_Score', ascending=False)

import pandas as pd
output_filename = 'Internship_Shortlist.xlsx'
with pd.ExcelWriter(output_filename) as writer:
    shortlisted_final.to_excel(writer, sheet_name='Ranked_Shortlist', index=False)

print(f"✅ Successfully exported 'shortlisted_final' to {output_filename} in the sheet 'Ranked_Shortlist'.")
print("You can find this file in your Colab sidebar.")