# -*- coding: utf-8 -*-
"""Clean_logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iGC9Z-MVYr6NbJ0TFSHrut61cwhna_Et
"""

import pandas as pd
import numpy as np
data = {
    'Incident_ID': ['INC-1002', 'INC-1003', 'INC-1005', 'INC-1010'],
    'Source': ['Payment_Gateway', 'Customer_Support', 'Server_Monitor', np.nan],
    'Raw_Severity': ['High', 'Medium', np.nan, 'Critical'],
    'Impact_Scope': [np.nan, 4, 7, 10],
    'Urgency_Level': [10, 3, 8, 10],
    'Reliability': [0.95, np.nan, 0.85, 1.00]
}

df = pd.DataFrame(data)
def clean_incident_data(df):
    df['Source'] = df['Source'].fillna('Unknown_Source')
    df['Raw_Severity'] = df['Raw_Severity'].fillna('Unknown_Severity')
    df['Impact_Scope'] = df['Impact_Scope'].fillna(df['Impact_Scope'].median())
    df['Urgency_Level'] = df['Urgency_Level'].fillna(df['Urgency_Level'].median())
    df['Reliability'] = df['Reliability'].fillna(0.5)
    return df
df_cleaned = clean_incident_data(df)

print("df_cleaned has been re-created.")